BBBBBBB BBBBBBBBBB
BBBBB BBBBB
XXX XXXXXXX
BBBBBBBB
BBBBB BB

XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXX
    BBBBB BBBBBBB

    BBBBBBBB
    XXXXXX
XXXXXX

BBBBBBBB
