BBBBBBB BBBBBBBBBB
BBBBB BBBBB
XXXXXX
BBBBBBBB
BBBBB BB
XXXX
XXXX
XXXX
XXXX
XXXX
XXXXXXXX
BB BBBBBBBBBB
    XXXXXXXXX XXXX XXX XXXXXXXXXXXXXXXXX
BBBB
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	BBBBBBBBBB
        XXXXXXXXXX XXXXX XXXX XXXXXXX XX XXXXXXXXXXXX
	XXXX
	
	
	XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
BBBBB
XXXXXXXXX
XXXX
XXXX
XXXX
BBBBBBBB
