# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0006_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='Type',
            field=models.CharField(choices=[('Emotional', 'Emotional'), ('Academic', 'Academic'), ('Business', 'Business')], max_length=30),
        ),
    ]
